server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssmp?serverTimezone=UTC
    username: root
    password: 123456
mybatis-plus:
  global-config:
    db-config:
#      数据库主键自增
      id-type: auto
  configuration:
#      开启mybatis-plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl